version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 3030:3030
    networks:
      - api-net
    depends_on:
      - mysqldb
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/video?allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password=1234
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - api-net
    environment:
      MYSQL_DATABASE: video
      MYSQL_ROOT_PASSWORD: Amila_Rpw
networks:
  api-net: